### ISSUE TITLE
Update for Dart 2

### ISSUE THREAD

**Issue by andyundso** [wrike/sentry_client#7]
Hello everyone

Are there any plans from your side to make this package compatible with the latest Dart packages? I got some errors during our build because JSON.encode is now jsonEncode and little things like that.

Best regards.

**Comment by Keksinautin** [comment]
Hi andyundso,

Thank you. Sorry for the long silence. I will check compatibility with the latest Dart version and fix all problems today or tomorrow. 

Best regards.

**Comment by andyundso** [comment]
Hi Keksinautin

No worries and thanks for the reply. Looking forward to the update. :)

Best regards

**Comment by Keksinautin** [comment]
Hi @andyundso 

I have merged the request with fixes for Dart 2. But unfortunately I can not publish the package and I do not understand why. I have posted the [issue](https://github.com/dart-lang/pub-dartlang-dart/issues/1495) and now I am waiting for response, sorry. 

Best regards

**Comment by Keksinautin** [comment]
@andyundso I have successfully published the new [sentry_client version](https://pub.dartlang.org/packages/sentry_client/versions/4.2.0) can you check, please, is everythink ok for you?

**Comment by andyundso** [comment]
Hello @Keksinautin 

Thanks for the update, the package is now working with Dart 2, thank you very much.

Best regards

**Comment by andyundso** [comment]
Okay, sorry, one last thing:

Is it possible that you could pump the version for the UUID dependency from 0.5.3 to at least 1.0? 0.5.3 is not compatible with Dart 2.0.

Thank you very much and best regards.

**Comment by Keksinautin** [comment]
@andyundso sure, I have just published `4.2.1` with the `uuid: ^1.0.0` dependence. Please, try it.  
Thank you.

**Comment by andyundso** [comment]
@Keksinautin thanks for your efforts, looks good now. Cheers.

**Comment by Keksinautin** [comment]
@andyundso you are welcome, and thank you!
